name: RC to Develop Integration

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/15 * * * *" # should run every 20 minutes

jobs:
  integrate-rc-to-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Integrate RC to Develop
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: bash .github/workflows/integrate-rc-to-develop.sh
