on:
  schedule:
    - cron: "*/5 * * * *" # Testing
  workflow_dispatch:

name: Nightly Automated Builds

jobs:
  create-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tags for target branches
        run: |
          chmod +x .github/workflows/create-nightly-tags.sh
          .github/workflows/create-nightly-tags.sh
